---
    - name: add phantomjs 2.0 ppa
      apt_repository: repo='ppa:tanguy-patte/phantomjs'
      sudo: yes

    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: install phantomjs 2.0
      sudo: yes
      apt: pkg=phantomjs
