---
    # Manual: install aws-cli and aws configure credentials

    - name: Check if letsencrypt download exists
      stat: path=/home/ubuntu/letsencrypt
      sudo: yes
      register: stat_result

    - name: Check if letsencrypt domain folder exists
      stat: path=/etc/letsencrypt/live/{{ domain_name }}
      sudo: yes
      register: stat_result2

    - name: Check if letsencrypt live folder exists
      stat: path=/etc/letsencrypt/live
      sudo: yes
      register: stat_result3

    - name: Download letsencrypt
      command: git clone https://github.com/letsencrypt/letsencrypt
      when: stat_result.stat.exists == False

    - name: Stop nginx
      sudo: yes
      service: name=nginx state=stopped enabled=yes

    - name: Move current default nginx sites file
      sudo: yes
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

    - name: Configure nginx to serve tmp certbot public_html folder
      sudo: yes
      copy: src=default dest=/etc/nginx/sites-available owner=root group=root mode=0644 force=yes

    - name: Make directory nginx serves
      sudo: yes
      command: mkdir -p /tmp/certbot/public_html

    - name: Start nginx
      sudo: yes
      service: name=nginx state=started enabled=yes

    - name: Generate certificate
      sudo: yes
      command: /home/ubuntu/letsencrypt/letsencrypt-auto certonly --webroot -w /tmp/certbot/public_html -d {{ domain_name }} --email lmis.open@gmail.com --agree-tos --force-renew
      when: stat_result2.stat.exists == False

    - name: Auto-renew script for master
      sudo: yes
      copy: src=auto_renew_ssl dest=/home/ubuntu owner=root group=root mode=0744 force=no

    - name: Creates auto renew certificate job for master
      sudo: yes
      cron: minute="0" hour="0" day="1" month="*/2" weekday="*"
            name="auto renew certificate"
            user="root"
            job="/home/ubuntu/auto_renew_ssl"

    - name: Upload certificate to AWS
      sudo: yes
      command: aws iam upload-server-certificate --server-certificate-name {{ cert_name }} --certificate-body file:///etc/letsencrypt/live/{{ domain_name }}/cert.pem --private-key file:///etc/letsencrypt/live/{{ domain_name }}/privkey.pem

    - name: Replace certificate on ELB
      sudo: yes
      command: aws elb set-load-balancer-listener-ssl-certificate --load-balancer-name {{ elb_name }} --load-balancer-port 443 --ssl-certificate-id {{ arn_cert }}





