---
 - name: uninstall older docker packages
   pip:
     name: "{{ item }}"
     state: absent
   with_items:
     - docker-py
     - docker

 - name: install docker package
   pip:
     name: docker

 - name: creating docker group
   group: name=docker state=present
   become: true

 - name: adding current user to docker group
   user: name=ubuntu groups=docker append=yes
   become: true
