---
 - name: install pip
   apt:
     name: python-pip
     update_cache: yes

 - name: uninstall older python-docker packages
   pip:
     name: "{{ item }}"
     state: absent
   with_items:
     - docker-py
     - docker

 - name: install docker
   shell: curl -sSL https://get.docker.com/ | sh

 - name: install python-docker packages
   pip:
     name: docker

 - name: create docker group
   group: name=docker state=present

 - name: add current user to docker group
   user: name={{ ansible_user }} groups=docker append=yes
