---
 - name: install docker
   shell: curl -sSL https://get.docker.com/ | sh

 - name: creating docker group
   group: name=docker state=present
   become: true

 - name: adding current user to docker group
   user: name=ubuntu groups=docker append=yes
   become: true
