---
- name: Ensure database is created
  postgresql_db: name={{dbname}}
  sudo_user: postgres

- name: Ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{DBPASSWORD}} priv=ALL
  sudo_user: postgres

- name: Ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=SUPERUSER,NOCREATEDB
  sudo_user: postgres

- name: Grant postgres privileges
  command: "psql -c 'GRANT postgres TO {{dbuser}}' -d {{dbname}}"
  sudo_user: postgres

- name: Delete schema public
  command: "psql -c 'drop SCHEMA  IF EXISTS public CASCADE' -d {{dbname}}"
  sudo_user: postgres

- name: Create schema public
  command: "psql -c 'CREATE SCHEMA public AUTHORIZATION  {{dbuser}}' -d {{dbname}}"
  sudo_user: postgres

- name: Delete schema atomfeed
  command: "psql -c 'drop SCHEMA  IF EXISTS atomfeed CASCADE' -d {{dbname}}"
  sudo_user: postgres

- name: Create schema atomfeed
  command: "psql -c 'CREATE SCHEMA atomfeed AUTHORIZATION  {{dbuser}}' -d {{dbname}}"
  sudo_user: postgres