---
- name: Stop app
  command: "service tomcat stop"

- name: Stop all postgres process
  command: "pkill postgres"
  ignore_errors: yes

- name: Start postgres server
  command: "service postgresql start"
  become: yes

- name: Termine sessions
  command: psql -U postgres -c "select pg_terminate_backend(pid) from pg_stat_activity where datname='{{dbname}}'"
  ignore_errors: yes

- name: Copy database backup
  copy: "src=backups/ dest=~/backups"

- name: Extract database backup
  command: sh -c "find -type f -name *.gz | xargs tar xvfz"

- name: Copy sql scripts
  copy: "src=sql/ dest=~/"

- name: Drop current DB
  command: "dropdb {{dbname}} -U {{dbuser}}"
  ignore_errors: yes

- name: Delete schema public
  command: "psql -U postgres -c 'drop SCHEMA  IF EXISTS public CASCADE' -d {{dbname}}"
  ignore_errors: yes

- name: Delete schema atomfeed
  command: "psql -U postgres -c 'drop SCHEMA  IF EXISTS atomfeed CASCADE' -d {{dbname}}"
  ignore_errors: yes

- name: Restoring database
  command: sh -c "find -type f -name 'openlmis-backup-*.sql' | xargs psql -U postgres -f"

- name: Change passwords
  command: sh -c "find -type f -name 'change_passwords.sql' | xargs psql {{ dbname }} -U {{ dbuser }} -f"

- name: Cleaning up
  command: "rm -rf ~/backup ~/sql ~/*.sql"
  become: yes

- name: Start app
  command: "sudo service tomcat start"
  become: yes
