---
- name: Stop app
  command: "service tomcat stop"

- name: Stop all postgres process
  command: "pkill postgres"

- name: Start postgres server
  command: "service postgresql start"
  become: yes

- name: Termine sessions
  command: psql -U postgres -c "select pg_terminate_backend(pid) from pg_stat_activity where datname='{{dbname}}'"

- name: Drop current DB
  command: "dropdb {{dbname}} -U {{dbuser}}"
  become: yes

- name: Create DB
  command: "createdb {{dbname}} -U {{dbuser}}"
  become: yes

- name: Copy database backup
  copy: "src=backups/*.sql dest=/home/ubuntu/"
  become: yes

- name: Copy sql scripts
  copy: "src=sql/change_passwords.sql dest=/home/ubuntu/"
  become: yes

- name: Load anonymized prod data
  command: "pgrestore -Fc --file /home/ubuntu/openlmis-backup-*"

- name: Change passwords
  command: "psql {{dbname}} -U {{dbuser}} --file /home/ubuntu/change_passwords.sql"

- name: Cleaning up
  command: "rm -rf /home/ubuntu/*.sql /home/ubuntu/openlmis-backup-*"
  become: yes

- name: Start app
  command: "sudo service tomcat start"
  become: yes
