---
# - include: add-apt-repo-for-postgres.yml
# - include: psql-client.yml
# - include: postgres-server.yml
#   when: install_postgres_server
#
- name: check postgres is installed
  shell: /usr/bin/test "$(which psql 2> /dev/null)" = /usr/bin/psql
  register: wanted_version_installed
  failed_when: wanted_version_installed.rc > 1

- name: Add Postgres repo to sources list
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present
  sudo: yes
  when: wanted_version_installed.rc == 1

- name: Add key for Postgres repo
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  sudo: yes
  when: wanted_version_installed.rc == 1

- name: install postgresql packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  tags: [packages]
  with_items:
    - "postgresql-client-{{ postgres_version }}"
  when: wanted_version_installed.rc == 1

- name: install postgresql packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  tags: [packages]
  with_items:
    - "postgresql-{{ postgres_version }}"
    - libpq-dev
    - "postgresql-contrib-{{ postgres_version }}"
    - libxslt-dev
    - libxml2-dev
  when: wanted_version_installed.rc == 1




# To do - add tasks to create a login on the local postgres db for user: Vagrant
