---
- include: add-apt-repo-for-postgres.yml

- name: Install postgresql
  apt: pkg='{{item}}' state=present force=yes
  with_items:
    - libpq-dev
    - postgresql-client
    - 'postgresql-contrib-{{ postgres_version }}'
    - 'postgresql-{{ postgres_version }}'
    - python-psycopg2
  become: yes


- name:  Initialize the directories of postgres instance
  tags: postgres
  file: path=/app/postgres/data owner=postgres group=postgres mode=0700 state=directory

- name: Set env
  copy: src=.bashrc dest=/var/lib/postgresql/.bashrc owner=postgres group=postgres


- name: Setup the env variables
  template: src='master/{{item}}' dest={{postgres_home}}{{item}} owner=postgres group=postgres
  when: region == 'uat-master'
  with_items:
     - pg_hba.conf
     - postgresql.conf

- name: Setup the env variables
  template: src='slave/{{item}}' dest={{postgres_home}}{{item}} owner=postgres group=postgres
  when: region == 'uat-slave'
  with_items:
     - pg_hba.conf
     - postgresql.conf
     - recovery.conf

- name: Start postgresql
  shell: /etc/init.d/postgresql start
  ignore_errors: yes
