---
- include: add-apt-repo-for-postgres.yml

- name: Install postgresql
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600 force=yes
  with_items:
    - libpq-dev
    - postgresql-client
    - postgresql-contrib-{{ postgres_version }}
    - postgresql-{{ postgres_version }}
    - python-psycopg2


- name:  Initialize the dirctories of postgres instance
  tags: postgres
  file: path=/app/postgres/data owner=postgres group=postgres mode=0700 state=directory