---
- name: Copy artifact
  copy: "src=openlmis_portal//{{ cubes_artifact }} dest={{ cubes_home }}/"
  become: yes

- name: Stop cubes service
  service: name=cubes state=stopped

- name: Unzip artifact
  unarchive: "src={{ cubes_home }}/{{ cubes_artifact }} dest={{ cubes_home }}/"
  become: yes

- name: Restart cubes service
  service: name=cubes state=restarted