---
- name: Copy artifact
  copy: 'src={{portal_source}}//{{ cubes_artifact }} dest={{ cubes_home }}/'
  become: yes

- name: Stop cubes service
  command: 'service cubes stop'
  become: yes

- name: Unzip artifact
  unarchive: 'src={{ cubes_home }}/{{ cubes_artifact }} dest={{ cubes_home }}/ copy=no group=middleware owner=middleware'
  become: yes

- name: Restart cubes service
  command: 'service cubes restart'
  become: yes
