---
  - name: Update apt cache
    apt: update-cache=yes cache_valid_time=86400
    sudo: yes

  - name: Install nfs-common
    sudo: yes
    apt: pkg=nfs-common state=latest

  - name: Mount NFS
    sudo: yes
    command: mount {{ nfs_server_host }}:/app/tomcat/openlmis/emailattachment /app/tomcat/openlmis/emailattachment