FROM gocd/gocd-agent-ubuntu-16.04:v17.10.0

RUN curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install nodejs && \
    apt-get install bzip2
