version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8154:8154
    volumes:
      - godata_server_db:/godata/db
      - godata_server_logs:/godata/logs
      - godata_server_artifacts:/godata/artifacts

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    depends_on:
      - db
      - server
    environment:
      - GO_SERVER_URL=https://server:8154/go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /godata

  db:
    image: "postgres:9.4"

volumes:
  godata_server_db:
  godata_server_logs:
  godata_server_artifacts:
