FROM gocd/gocd-agent-ubuntu-16.04:v17.10.0

RUN apt-get update \
&&  apt-get install wget \
&&  wget https://download.docker.com/linux/static/stable/x86_64/docker-17.03.0-ce.tgz \
&&  tar xzvf docker-17.03.0-ce.tgz \
&&  cp docker/docker /usr/bin/ \
&&  rm -rf docker docker-17.03.0-ce.tgz \
&&  groupadd docker \
&&  usermod -aG docker go
