version: '3.3'
services:
  server:
    image: siglus/gocd_server:0.0.2
    ports:
      - 8154:8154
    volumes:
      - godata_server_db:/godata/db
      - godata_server_logs:/godata/logs
      - godata_server_artifacts:/godata/artifacts

  portal_agent:
    depends_on:
      - server
      - db
    image: siglus/gocd_agent:0.1.0
    environment:
      - GO_SERVER_URL=https://server:8154/go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /godata

  mobile_agent:
    depends_on:
      - server
      - db
    image: siglus/gocd_agent:0.1.0-mobile
    environment:
      - GO_SERVER_URL=https://server:8154/go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /godata

  db:
    image: "postgres:9.4"

volumes:
  godata_server_db:
  godata_server_logs:
  godata_server_artifacts:
