---
- hosts: qa-master
  connection: ssh
  sudo: yes
  roles:
    - configuration
    - flyway
    - package
    - cubes
  vars:
    region: qa-master

- hosts: qa-slave
  connection: ssh
  sudo: yes
  roles:
    - configuration
    - package
    - cubes
  vars:
    region: qa-slave