---
- hosts: prodweb-master
  connection: ssh
  sudo: yes
  roles:
    - configuration
    - flyway
    - package
    - cubes
    - db-migration
  vars:
    region: prod-master

- hosts: prodweb-slave
  connection: ssh
  sudo: yes
  roles:
    - configuration
    - flyway
    - package
    - cubes
    - db-migration
  vars:
    region: prod-slave