---
- hosts: prodweb-master
  connection: ssh
  sudo: yes
  roles:
    - rollback
  vars:
    region: prod-master

- hosts: prodweb-slave
  connection: ssh
  sudo: yes
  roles:
    - rollback
  vars:
    region: prod-slave