---
- name: git clone provision code
  git:
    repo: https://github.com/SIGLUS/openlmis-devops.git
    dest: /home/ubuntu/siglus_infra
    update: yes

- name: removing previous gocd services
  command: docker-compose down
  ignore_errors: yes
  args:
    chdir: /home/ubuntu/siglus_infra/ci/gocd

- name: initialize gocd services
  command: docker-compose up -d
  args:
    chdir: /home/ubuntu/siglus_infra/ci/gocd
