---
- name: install docker-py package
  pip:
    name: docker-py

- name: copy docker-compose file
  copy:
    src: docker-compose.aws.yml
    dest: /home/ubuntu/docker-compose.aws.yml

- name: removing previous gocd services
  command: docker-compose -f docker-compose.aws.yml down
  ignore_errors: yes
  args:
    chdir: /home/ubuntu/

- name: login docker hub
  docker_login:
    username: siglus
    password: "{{docker_hub_password}}"
    email: siglusuio@thoughtworks.com

- name: initialize gocd services
  command: docker-compose -f docker-compose.aws.yml up -d
  args:
    chdir: /home/ubuntu/
