---
- name: create gocd directory
  file:
    path: /home/ubuntu/siglus
    state: directory

- name: copy docker-compose folder
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu/siglus

- name: copy credentials variables
  template:
    src: "credentials.env"
    dest: "/home/ubuntu/siglus/"
    owner: ubuntu
    group: ubuntu

- name: cleaning up siglus services
  command: docker-compose down
  args:
    chdir: /home/ubuntu/siglus
  ignore_errors: yes

- name: initialize siglus services
  command: docker-compose up -d --remove-orphans
  args:
    chdir: /home/ubuntu/siglus

- name: cleaning up siglus services
  command: rm credentials.env
  args:
    chdir: /home/ubuntu/siglus
