---
- name: Launch ec2 instance
  ec2:
    key_name: "{{ keypair_name }}"
    instance_type: m4.large
    image: "{{ image_id }}"
    wait: yes
    group_id: "{{ group_id }}"
    count: 1
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    region: "{{ region }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    instance_tags:
      Name: "{{ instance_name }}"
  register: ec2

- name: Add new instace to the ansible-playbook in-memory inventory
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: "{{ groupname }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name  }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances  }}"
