---
- name: Copy artifacts
  copy: "src=libs//{{ item }} dest={{application_dir}}/{{application_name}}/db/"
  with_items:
    - db.jar
    - migration.jar
  become: yes

- name: Remove the directories of sql instance
  command: "rm -rf {{flyway_install_dir}}/sql/{{item}}"
  with_items:
      - db
      - migration
  become: yes

- name: Initialize the directories of sql instance
  file: path={{flyway_install_dir}}/sql/{{item}} mode=0755 state=directory
  with_items:
      - db
      - migration
  become: yes

- name: Unzip sql file jar
  command: "unzip {{application_dir}}/{{application_name}}/db/{{item}}.jar -d {{flyway_install_dir}}/sql/{{item}}"
  with_items:
      - db
      - migration
  become: yes

- name: Migrate db module
  command: "{{flyway_install_dir}}/flyway
  -url=jdbc:postgresql://{{dbhost_master}}:{{dbport}}/{{dbname}}
  -schemas=public,atomfeed
  -user={{dbuser}}
  -password={{dbpassword}}
  -table=schema_version
  -placeholderReplacement=false
  -locations=filesystem:{{flyway_install_dir}}/sql/db
  -X
  migrate"

- name: Migrate migration module
  command: "{{flyway_install_dir}}/flyway
  -url=jdbc:postgresql://{{dbhost_master}}:{{dbport}}/{{dbname}}
  -schemas=public,atomfeed
  -user={{dbuser}}
  -password={{dbpassword}}
  -table=migration_schema_version
  -placeholderReplacement=false
  -baselineOnMigrate=true
  -locations=filesystem:{{flyway_install_dir}}/sql/migration
  -X
  migrate"
