- name: Step 1 > Initialize the dirctories of db script
  tags: flyway
  file: path={{application_dir}}/db owner=postgres group=postgres mode=0755 state=directory
  sudo_user: postgres

- name: Step 2 > Install flyway on server
  copy: src=flyway/ dest={{flyway_install_dir}}


- name: Step 3 > Copy configuration file
  template: src=flyway.properties dest={{flyway_install_dir}}/conf/flyway.conf

- name: Step 4 > Make the flyway command  executable
  shell: chmod +x /{{flyway_install_dir}}/flyway

- name: Step 5 > change owner
  command: "psql -c 'alter schema public owner to openlmis' -d open_lmis"
  sudo_user: postgres

- name: Step 6 > Create schema
  command: "{{flyway_install_dir}}/flyway
  -url=jdbc:postgresql://{{dbhost}}:{{dbport}}/{{dbname}}
  -schemas=public,atomfeed
  -user={{dbuser}}
  -password={{DBPASSWORD}}
  -table=schema_version
  -X
  migrate"



