---
- name: Copy dependent files
  copy: "src=env//{{ hostvars[inventory_hostname]['role'] }}/ dest={{application_dir}}/{{application_name}}/properties owner=middleware group=middleware mode=0644"
  become: yes

- name: Copy scripts
  copy: "src=scripts/ dest=/tmp/"

- name: Replace configuration files
  command: ruby /tmp/replace_configuration.rb

