---
- name: Copy configuration files
  template:
    src: "{{ hostvars[inventory_hostname]['role'] }}/{{ item }}"
    dest: "{{ application_dir }}/{{ application_name }}/properties/{{ item }}"
    owner: middleware
    group: middleware
  with_items:
    - app.properties
    - atomfeed.properties
    - default.properties
    - mailing.properties
  become: yes
