---
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - curl
        - vim
        - libxslt1-dev
        - libxml2-dev
        - zip
        - unzip
        - python-pip
        - python-psycopg2
        - apg
        - mercurial
        - git
        - software-properties-common

    - name: add apt-add-repository
      sudo: yes
      apt_repository: repo='ppa:ansible/ansible' state=present

    - name: Install ansible
      sudo: yes
      apt: pkg=ansible

    - name: Install Java 1.7
      apt: pkg=openjdk-7-jdk state=present

    - name: Ensure that ansible_cache_dir directory exists
      file: path={{ ansible_cache_dir }} state=directory
      sudo: yes