- name: Replace all pg password in secrets properties file
  command: 'sed -i "s|postgresPwd|$PGPASSWORD|g" {{application_dir}}/{{application_name}}/properties/secrets.properties'

- name: Replace all pg username in secrets properties file
  command: 'sed -i "s|postgresUname|$POSTGRES_USER_NAME|g" {{application_dir}}/{{application_name}}/properties/secrets.properties'

- name: Replace all pg host in secrets properties file
  command: 'sed -i "s|postgresHost|$POSTGRES_HOST|g" {{application_dir}}/{{application_name}}/properties/secrets.properties'

- name: Replace mail url in secrets properties file
  command: 'sed -i "s|mailBaseUrl:mailPort|$MAILURL|g" {{application_dir}}/{{application_name}}/properties/secrets.properties'

- name: Replace mail pwd in secrets properties file
  command: 'sed -i "s|mailPwd|$OPENLMIS_MAILPW|g" {{application_dir}}/{{application_name}}/properties/secrets.properties'

- name: Replace app url in secrets properties file
  command: 'sed -i "s|appUrl:appPort|$APPURL|g" {{application_dir}}/{{application_name}}/properties/secrets.properties'

