---
- name: Rollback web deployment > Stop tomcat service
  service: name=tomcat state=stop

- name:  Rollback web deployment > Rollback artifact to previous version
  command: "mv {{application_dir}}/{{application_name}}/artifact_last/ROOT.war
            {{application_dir}}/{{application_name}}/webapps/ROOT.war"

- name: Rollback web deployment > Restart tomcat service
  service: name=tomcat state=restarted

- name: Rollback web deployment > Check application runs
  wait_for: port={{ http_port }}
