---
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - curl
        - vim
        - zip
        - unzip
        - git
        - ruby

    - name: Install Java 1.7
      apt: pkg=openjdk-7-jdk state=present

    - name: Ensure that ansible_cache_dir directory exists
      file: path={{ ansible_cache_dir }} state=directory
      sudo: yes
