---
- hosts: local
  connection: local
  sudo: yes
  roles:
    - base
    - tomcat
    - nodejs
    - gradle
    - postgres
    - grunt
    - karma
    - ansible-role-jenkins
    - android
    - ansible-role-ruby
