---
- hosts: qa-master
  connection: ssh
  sudo: yes
  roles:
    - base
    - tomcat
    - postgres
    - postgres-init
    - flyway
    - cubes
    - phantom
    - nfs_server
    - letsencrypt
  vars:
    region: qa-master

- hosts: qa-slave
  connection: ssh
  sudo: yes
  roles:
    - base
    - tomcat
    - cubes
    - phantom
    - nfs_client
  vars:
    region: qa-slave
