---
- hosts: all
  sudo: yes
  roles:
    - base
    - oracle-java
    - nodejs
    - gradle
    - postgres
    - grunt
    - karma
    - { role: alexanderjardim.tomcat }
    - { role: geerlingguy.jenkins }
