---
- name: Stop all postgres process
  command: "pkill postgres"

- name: Drop current DB
  command: "dropdb {{dbname}}"
  sudo_user: postgres

- name: Create DB
  command: "createdb {{dbname}}"
  sudo_user: postgres

- name: Load anonymized prod data
  command: "psql {{dbname}} -U {{dbuser}} --file {{prod_data_file_location}}"
  sudo_user: postgres