---
- name: Stop app
  command: "service tomcat stop"

- name: Stop all postgres process
  command: "pkill postgres"

- name: Start postgres server
  command: "service postgresql start"

- name: Drop current DB
  command: "dropdb {{dbname}} -U {{dbuser}}"
  sudo_user: postgres

- name: Create DB
  command: "createdb {{dbname}} -U {{dbuser}}"
  sudo_user: postgres

- name: Load anonymized prod data
  command: "psql {{dbname}} -U {{dbuser}} --file {{prod_data_without_MV_file_location}}"
  sudo_user: postgres

- name: Change passwords
  command: "psql {{dbname}} -U {{dbuser}} --file change_passwords.sql"

- name: Start app
  command: "sudo service tomcat start"
