- name: Step 1 > Remove the dirctories of sql instance
  command: "rm -rf {{flyway_install_dir}}/sql/one-time-migration"

- name: Step 2 > Initialize the dirctories of sql instance
  file: path={{flyway_install_dir}}/sql/one-time-migration mode=0755 state=directory

- name: Step 3 > move Sql file
  copy: src=db-migration/migration/ dest={{flyway_install_dir}}/sql/one-time-migration

- name: Step 4 > migrate db module
  command: "{{flyway_install_dir}}/flyway
  -url=jdbc:postgresql://{{dbhost_master}}:{{dbport}}/{{dbname}}
  -schemas=public,atomfeed
  -user={{dbuser}}
  -password={{DBPASSWORD}}
  -table=one_time_migration_schema_version
  -placeholderReplacement=false
  -locations=filesystem:{{flyway_install_dir}}/sql/one-time-migration
  -X
  migrate"